"""Add email_subscriptions table

Revision ID: ca82fb7ef8dd
Revises: ce9436c26034
Create Date: 2026-03-30 01:46:10.554897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca82fb7ef8dd'
down_revision: Union[str, None] = 'ce9436c26034'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('notify_restock', sa.Boolean(), nullable=False),
    sa.Column('notify_withdraw', sa.Boolean(), nullable=False),
    sa.Column('notify_low_stock', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_subscriptions_id'), 'email_subscriptions', ['id'], unique=False)
    op.create_index(op.f('ix_email_subscriptions_user_id'), 'email_subscriptions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_email_subscriptions_user_id'), table_name='email_subscriptions')
    op.drop_index(op.f('ix_email_subscriptions_id'), table_name='email_subscriptions')
    op.drop_table('email_subscriptions')
    # ### end Alembic commands ###
